# Generated by Django 2.2.16 on 2021-02-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_dob',
            new_name='date_of_arrival',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='passenger_name',
        ),
    ]
