# Generated by Django 2.2.19 on 2021-03-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdb', '0004_student_mode_of_transport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='BOOKING',
        ),
    ]
