# Generated by Django 3.1.6 on 2021-03-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210318_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
