# Generated by Django 2.2.16 on 2021-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdb', '0002_auto_20210222_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passenger_age',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='student',
            name='passenger_mobile_no',
            field=models.IntegerField(default=2),
        ),
    ]
