# Generated by Django 2.2.16 on 2021-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdb', '0003_auto_20210222_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mode_of_transport',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
