# Generated by Django 3.1.6 on 2021-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('seat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FLIGHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('seat', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='TRAIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('seat', models.IntegerField(default=15)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
