# Generated by Django 3.1.6 on 2021-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
